---
# Copyright (C) 2020 Stefan Hornburg (Racke) <racke@linuxia.de>
# SPDX-License-Identifier: Artistic-2.0

- name: Preseed values for installation
  debconf:
    name: "sympa"
    question: "{{ item.name | default('sympa') }}/{{ item.question }}"
    value: "{{ item.value }}"
    vtype: "{{ item.type | default('string') }}"
  with_items:
    - question: "listmaster"
      value: "{% if sympa_listmaster is string %}{{ sympa_listmaster }}{% else %}{{ sympa_listmaster | join(',') }}{% endif %}"
    - question: "hostname"
      value: "{{ sympa_domain }}"
    - name: wwsympa
      question: "wwsympa_url"
      value: "http://{{ sympa_domain }}/sympa"
  when: ansible_os_family == 'Debian'
  register: ansible_debconf_preseed
  tags:
    - debconf
    - preseed

- name: Ensure that dbconfig is installed
  apt:
    name: dbconfig-common
  when: ansible_os_family == 'Debian'
  tags:
    - debconf
    - dbconfig

- name: Create configuration file for dbconfig
  template:
    src: dbconfig-common.j2
    dest: /etc/dbconfig-common/sympa.conf
    owner: root
    group: root
    mode: 0600
  register: sympa_dbconfig_results
  when: ansible_os_family == 'Debian'
  tags:
    - debconf
    - dbconfig

- name: Install Sympa from distribution package
  package:
    name: sympa
  become: yes
  when: sympa_package_file is not defined
  register: sympa_package_distribution_results
  tags:
    - sympa

- name: Create temporary directory for package file
  tempfile:
    state: directory
  register: sympa_tempdir
  when: sympa_package_file is defined
  tags:
    - sympa

- name: Copy package file to target
  copy:
    src: "{{ sympa_package_file }}"
    dest: "{{ sympa_tempdir.path }}/{{ sympa_package_file | basename }}"
  when: sympa_package_file is defined
  tags:
    - sympa

- name: Install Sympa from package file (Debian)
  apt:
    deb: "{{ sympa_tempdir.path }}/{{ sympa_package_file | basename }}"
  when: sympa_package_file is defined
  register: sympa_package_file_results
  tags:
    - sympa

- name: Set variable for Sympa command
  set_fact:
    sympa_command: "{{ sympa_package_command }}"
