---
# Copyright (C) 2020 Stefan Hornburg (Racke) <racke@linuxia.de>
# SPDX-License-Identifier: Artistic-2.0

- name: Install Sympa from distribution package
  package:
    name: sympa
  tags:
    - sympa
