---
# Copyright (C) 2020 Stefan Hornburg (Racke) <racke@linuxia.de>
# SPDX-License-Identifier: Artistic-2.0

- name: Install cpanm
  package:
    name: "{{ sympa_cpanm_package }}"

- name: Install Perl modules
  command: cpanm --notest --installdeps "{{ sympa_source_directory }}"
